export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const DELETE_TOTAL_PRODUCTS = 'DELETE_TOTAL_PRODUCTS'
export const INIT_CART = 'INIT_CART'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT_BY_SLUG = 'GET_PRODUCT_BY_SLUG'
export const RESET_CART = 'RESET_CART'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
